In [1]:
import json
import random
from datetime import datetime, timedelta
from ucimlrepo import fetch_ucirepo, list_available_datasets
import numpy as np
import pandas as pd
from etl import UserGenerator
from feature_engineer import FeatureEngineer
from sklearn.linear_model import LogisticRegression
from train_mlflow import TrainMlflow
from train_mlflow_advance import TrainOptuna

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

# ETL

In [2]:
user_generator = UserGenerator(n_samples=25000)

In [3]:
ds = user_generator.create_dataset()
print(type(ds), isinstance(ds, tuple))

<class 'pandas.core.frame.DataFrame'> False

In [4]:
ds

,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...
541904,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

In [5]:
ds = user_generator.run_etl()

In [6]:
ds.info

<bound method DataFrame.info of                                 Description  Quantity      InvoiceDate  \
0        WHITE HANGING HEART T-LIGHT HOLDER         6   12/1/2010 8:26
1                       WHITE METAL LANTERN         6   12/1/2010 8:26
2            CREAM CUPID HEARTS COAT HANGER         8   12/1/2010 8:26
3       KNITTED UNION FLAG HOT WATER BOTTLE         6   12/1/2010 8:26
4            RED WOOLLY HOTTIE WHITE HEART.         6   12/1/2010 8:26
...                                     ...       ...              ...
541904          PACK OF 20 SPACEBOY NAPKINS        12  12/9/2011 12:50
541905         CHILDREN'S APRON DOLLY GIRL          6  12/9/2011 12:50
541906        CHILDRENS CUTLERY DOLLY GIRL          4  12/9/2011 12:50
541907      CHILDRENS CUTLERY CIRCUS PARADE         4  12/9/2011 12:50
541908        BAKING SET 9 PIECE RETROSPOT          3  12/9/2011 12:50

        UnitPrice  CustomerID         Country
0            2.55     17850.0  United Kingdom
1            3.39     17850.0  United Kingdom
2            2.75     17850.0  United Kingdom
3            3.39     17850.0  United Kingdom
4            3.39     17850.0  United Kingdom
...           ...         ...             ...
541904       0.85     12680.0          France
541905       2.10     12680.0          France
541906       4.15     12680.0          France
541907       4.15     12680.0          France
541908       4.95     12680.0          France

[541909 rows x 6 columns]>

In [7]:
ds.describe().T

,count,mean,std,min,25%,50%,75%,max
Quantity,541909.0,9.552250,218.081158,-80995.00,1.00,3.00,10.00,80995.0
UnitPrice,541909.0,4.611114,96.759853,-11062.06,1.25,2.08,4.13,38970.0
CustomerID,406829.0,15287.690570,1713.600303,12346.00,13953.00,15152.00,16791.00,18287.0

In [8]:
ds.columns

Index(['Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID',
       'Country'],
      dtype='object')

In [9]:
# Información base
print("Fecha mínima:", ds["InvoiceDate"].min())
print("Fecha máxima:", ds["InvoiceDate"].max())
print("Clientes únicos:", ds["CustomerID"].nunique())
print("Productos únicos:", ds["Description"].nunique())
print("Países:", ds["Country"].nunique())
ds["InvoiceDate"] = pd.to_datetime(ds["InvoiceDate"], errors="coerce")
print("Productos únicos:", ds["Description"].nunique())
print("Países:", ds["Country"].nunique())
print(f"Rango de fechas: {ds['InvoiceDate'].min().date()} → {ds['InvoiceDate'].max().date()}")

Fecha mínima: 1/10/2011 10:04
Fecha máxima: 9/9/2011 9:52
Clientes únicos: 4372
Productos únicos: 4223
Países: 38
Productos únicos: 4223
Países: 38
Rango de fechas: 2010-12-01 → 2011-12-09

# Feature Engineering

In [10]:
feature_engineer = FeatureEngineer(ds)

In [11]:
df_engineered = feature_engineer.run()

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\src\app\train\feature_engineer.py:52: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(self.historial_compra)   # <-- ahora acepta g

In [12]:
df_engineered

,Description,InvoiceDate,Country,Quantity,Revenue,UnitPrice,CustomerID,n_past_invoices,prev_date,recency_days,spend_prior,qty_prior,avg_ticket_prior,avg_qty_per_invoice_prior,next_date,days_to_next,y_repurchase_30d
0,MEDIUM CERAMIC TOP STORAGE JAR,2011-01-18 10:01:00,United Kingdom,74215,77183.60,1.04,12346.0,0,NaT,9999,0.00,0,0.000000,0.000000,2011-01-18 10:17:00,0.0,1
1,MEDIUM CERAMIC TOP STORAGE JAR,2011-01-18 10:17:00,United Kingdom,-74215,-77183.60,1.04,12346.0,1,2011-01-18 10:01:00,0,77183.60,74215,77183.600000,74215.000000,NaT,NaN,0
2,3D DOG PICTURE PLAYING CARDS,2010-12-07 14:57:00,Iceland,24,70.80,2.95,12347.0,0,NaT,9999,0.00,0,0.000000,0.000000,2010-12-07 14:57:00,0.0,1
3,AIRLINE BAG VINTAGE JET SET BROWN,2010-12-07 14:57:00,Iceland,4,17.00,4.25,12347.0,1,2010-12-07 14:57:00,0,70.80,24,70.800000,24.000000,2010-12-07 14:57:00,0.0,1
4,ALARM CLOCK BAKELIKE CHOCOLATE,2010-12-07 14:57:00,Iceland,4,15.00,3.75,12347.0,2,2010-12-07 14:57:00,0,87.80,28,43.900000,14.000000,2010-12-07 14:57:00,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
396480,SWISS CHALET TREE DECORATION,2011-10-12 10:23:00,United Kingdom,24,6.96,0.29,18287.0,63,2011-10-12 10:23:00,0,1739.84,1442,27.616508,22.888889,2011-10-12 10:23:00,0.0,1
396481,TREE T-LIGHT HOLDER WILLIE WINKIE,2011-10-12 10:23:00,United Kingdom,12,19.80,1.65,18287.0,64,2011-10-12 10:23:00,0,1746.80,1466,27.293750,22.906250,2011-10-28 09:29:00,15.0,1
396482,PAINTED METAL STAR WITH HOLLY BELLS,2011-10-28 09:29:00,United Kingdom,48,18.72,0.39,18287.0,65,2011-10-12 10:23:00,15,1766.60,1478,27.178462,22.738462,2011-10-28 09:29:00,0.0,1
396483,SET OF 3 WOODEN SLEIGH DECORATIONS,2011-10-28 09:29:00,United Kingdom,36,45.00,1.25,18287.0,66,2011-10-28 09:29:00,0,1785.32,1526,27.050303,23.121212,2011-10-28 09:29:00,0.0,1
396484,SWISS CHALET TREE DECORATION,2011-10-28 09:29:00,United Kingdom,24,6.96,0.29,18287.0,67,2011-10-28 09:29:00,0,1830.32,1562,27.318209,23.313433,NaT,NaN,0

# Modelando con MLFlow

In [13]:
import mlflow


experiment_name = "recompra-LogReg"
mlflow.set_tracking_uri("http://127.0.0.1:5000")
mlflow.set_experiment(experiment_name)

# Enable autologging for sklearn models
mlflow.sklearn.autolog(
    log_input_examples=True,
    log_model_signatures=True,
    log_models=True,
    disable=False,
    exclusive=False,
    disable_for_unsupported_versions=False,
    silent=False,
    max_tuning_runs=5
)

In [14]:
num_feats = [
    'recency_days','n_past_invoices','spend_prior','qty_prior',
    'avg_ticket_prior','avg_qty_per_invoice_prior','UnitPrice','Quantity','Revenue'
]
cat_feats = ['Country']

In [15]:


model = LogisticRegression(max_iter=500)

# 3) Instancia y entrena
trainer = TrainMlflow(
    df=df_engineered,
    numeric_features=num_feats,
    categorical_features=cat_feats,
    target_column='y_repurchase_30d',
    model=model,
    mlflow_setup={"tracking_uri": "file:./mlruns", "experiment_name": "OnlineRetail"}
)

pipeline, run_id = trainer.train()
trainer.pipeline = pipeline                  # <- necesario para save_model()
trainer.save_model("models/model.pkl")       # ✅ Modelo guardado en models/model.pkl

Rango total: 2010-12-01 08:26:00 → 2011-12-09 12:50:00 | cutoff: 2011-11-09 12:50:00
train_end: 2011-09-01 00:00:00
train: 224017 | test: 104368
pos_rate train=0.973 | test=0.979

2025/09/27 19:53:21 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 19:53:23 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 964.24it/s]
2025/09/27 19:53:52 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 19:53:56 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."

MLflow Run ID: 4c658bb0ecc84191b33c400c5a4d6a9b
Tracking URI: http://127.0.0.1:5000
Train Accuracy: 0.9728
Test Accuracy: 0.9794
🏃 View run monumental-bee-656 at: http://127.0.0.1:5000/#/experiments/2/runs/4c658bb0ecc84191b33c400c5a4d6a9b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
✅ Modelo guardado en models/model.pkl

'models/model.pkl'

In [ ]:
mlflow.set_experiment("recompra-optuna")

params = {
            'solver': ('categorical', ['lbfgs', 'liblinear', 'saga']),
            'C':      ('float', 1e-3, 1e2, True),
            'max_iter': ('int', 300, 1500),
            'class_weight': ('categorical', [None, 'balanced']),
            # solver-specific penalties are tricky to encode generically—start simple with l2
            'penalty': ('categorical', ['l2']),
}

trainer = TrainOptuna(
    df=df_engineered,
    numeric_features=num_feats,
    categorical_features=cat_feats,
    target_column='y_repurchase_30d',
    model_class=LogisticRegression,
    model_params={},                 
    n_trials=30,                     
    optimization_metric='roc_auc',   
    param_distributions=params,
)

best_pipeline, best_run_id, study = trainer.train()   # runs Optuna + logs to MLflow
trainer.save_model("models/modeloptuna.pkl")

[I 2025-09-27 19:53:59,548] A new study created in memory with name: optuna_LogisticRegression
c:\Users\gabri\OneDrive\ProyectoFinalMLOps\src\app\train\train_mlflow_advance.py:248: ExperimentalWarning: MLflowCallback is experimental (supported from v1.4.0). The interface can change in the future.
  mlflow_callback = MLflowCallback(
2025/09/27 19:53:59 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '677c33a1c5574cabb12c888e49949c11', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

Rango total: 2010-12-01 08:26:00 → 2011-12-09 12:50:00 | cutoff: 2011-11-09 12:50:00
train_end: 2011-09-01 00:00:00
train: 224017 | test: 104368
pos_rate train=0.973 | test=0.979
Starting Optuna optimization with 30 trials...
Optimizing for: roc_auc
Model type: LogisticRegression

2025/09/27 19:54:04 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
2025/09/27 19:55:35 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 2314.37it/s]

🏃 View run magnificent-tern-252 at: http://127.0.0.1:5000/#/experiments/3/runs/677c33a1c5574cabb12c888e49949c11
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 19:55:44 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 19:55:44,837] Trial 0 finished with value: 0.6790579528622713 and parameters: {'solver': 'saga', 'C': 0.013229998476237423, 'max_iter': 489, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 0 with value: 0.6790579528622713.
2025/09/27 19:55:45 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '09c8d03248f94e82a8c1cd9a620604c8', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 0 at: http://127.0.0.1:5000/#/experiments/4/runs/5096341747404d859e42d9fae0120f8f
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 19:55:47 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 19:55:49 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 914.59it/s]

🏃 View run adorable-sow-289 at: http://127.0.0.1:5000/#/experiments/4/runs/09c8d03248f94e82a8c1cd9a620604c8
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 19:55:57 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 19:55:57,066] Trial 1 finished with value: 0.6734201502924655 and parameters: {'solver': 'liblinear', 'C': 19.114542615600453, 'max_iter': 417, 'class_weight': None, 'penalty': 'l2'}. Best is trial 0 with value: 0.6790579528622713.
2025/09/27 19:55:57 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'aa4e802fade7421ca31d3bc7a15cf21c', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 1 at: http://127.0.0.1:5000/#/experiments/4/runs/db3cd0a1878d415f8baedff755ce99f2
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 19:55:59 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 19:56:01 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 2060.07it/s]

🏃 View run thundering-snail-539 at: http://127.0.0.1:5000/#/experiments/4/runs/aa4e802fade7421ca31d3bc7a15cf21c
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 19:56:08 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 19:56:08,621] Trial 2 finished with value: 0.6808973103277465 and parameters: {'solver': 'liblinear', 'C': 7.981228977990751, 'max_iter': 446, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 2 with value: 0.6808973103277465.
2025/09/27 19:56:08 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '00e05b51d85145f5845762ca3b6da8fe', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 2 at: http://127.0.0.1:5000/#/experiments/4/runs/df3fe7ca5d4f4224b4ad7d071d0097aa
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 19:56:11 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 19:56:12 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 2229.66it/s]

🏃 View run delicate-kit-832 at: http://127.0.0.1:5000/#/experiments/4/runs/00e05b51d85145f5845762ca3b6da8fe
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 19:56:20 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 19:56:20,072] Trial 3 finished with value: 0.6810140879132228 and parameters: {'solver': 'lbfgs', 'C': 0.08187154332812104, 'max_iter': 1011, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 3 with value: 0.6810140879132228.
2025/09/27 19:56:20 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'dea24013cc5f4d41a9304813e48a6445', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 3 at: http://127.0.0.1:5000/#/experiments/4/runs/552929278fd848968c189f372c9771b6
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 19:56:22 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 19:56:23 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1541.05it/s]

🏃 View run handsome-snake-381 at: http://127.0.0.1:5000/#/experiments/4/runs/dea24013cc5f4d41a9304813e48a6445
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 19:56:31 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 19:56:31,466] Trial 4 finished with value: 0.6794240874317414 and parameters: {'solver': 'lbfgs', 'C': 0.0031922929012305414, 'max_iter': 997, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 3 with value: 0.6810140879132228.
2025/09/27 19:56:31 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '6ed978fca53743e48af38560aa053112', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 4 at: http://127.0.0.1:5000/#/experiments/4/runs/7c9b0ef72cd643c8aa40c24cb47811a9
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 19:56:34 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 19:56:35 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1404.05it/s]

🏃 View run shivering-ox-203 at: http://127.0.0.1:5000/#/experiments/4/runs/6ed978fca53743e48af38560aa053112
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 19:56:44 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 19:56:44,129] Trial 5 finished with value: 0.6734280101908207 and parameters: {'solver': 'liblinear', 'C': 0.5052990747968685, 'max_iter': 856, 'class_weight': None, 'penalty': 'l2'}. Best is trial 3 with value: 0.6810140879132228.
2025/09/27 19:56:44 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '963129f4d3eb459fa4ffb8eff52161b9', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 5 at: http://127.0.0.1:5000/#/experiments/4/runs/9e454f6c780448eca74b5b7b48224553
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 19:56:46 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 19:56:47 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 2349.00it/s]

🏃 View run burly-hawk-853 at: http://127.0.0.1:5000/#/experiments/4/runs/963129f4d3eb459fa4ffb8eff52161b9
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 19:56:55 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 19:56:55,157] Trial 6 finished with value: 0.6792797386897738 and parameters: {'solver': 'lbfgs', 'C': 0.002801586788355018, 'max_iter': 1053, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 3 with value: 0.6810140879132228.
2025/09/27 19:56:55 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '405a8f8a9e2c4947a8ffd01172533f32', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 6 at: http://127.0.0.1:5000/#/experiments/4/runs/eaafa3b7ac7a401d9c08ccea6c62808a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 19:56:57 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 19:56:59 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1863.78it/s]

🏃 View run brawny-snipe-614 at: http://127.0.0.1:5000/#/experiments/4/runs/405a8f8a9e2c4947a8ffd01172533f32
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 19:57:07 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 19:57:07,295] Trial 7 finished with value: 0.6808991967033518 and parameters: {'solver': 'liblinear', 'C': 5.291187074112229, 'max_iter': 771, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 3 with value: 0.6810140879132228.
2025/09/27 19:57:07 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '633506b249004b44bc515991249b5208', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 7 at: http://127.0.0.1:5000/#/experiments/4/runs/d7129625bbab43d88a7989f8b62cb7bc
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 19:57:09 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 19:57:10 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1964.68it/s]

🏃 View run unruly-duck-81 at: http://127.0.0.1:5000/#/experiments/4/runs/633506b249004b44bc515991249b5208
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 19:57:18 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 19:57:18,825] Trial 8 finished with value: 0.6738940087557992 and parameters: {'solver': 'lbfgs', 'C': 3.6822481721098494, 'max_iter': 528, 'class_weight': None, 'penalty': 'l2'}. Best is trial 3 with value: 0.6810140879132228.
2025/09/27 19:57:19 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'ee9361951c984f05b70acd171e9568cf', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 8 at: http://127.0.0.1:5000/#/experiments/4/runs/75037bd7dfed4c9e86fea29e2f00dc25
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 19:57:21 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 19:57:22 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1420.63it/s]

🏃 View run handsome-bird-446 at: http://127.0.0.1:5000/#/experiments/4/runs/ee9361951c984f05b70acd171e9568cf
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 19:57:30 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 19:57:31,049] Trial 9 finished with value: 0.6734227975973608 and parameters: {'solver': 'liblinear', 'C': 15.818684063878212, 'max_iter': 934, 'class_weight': None, 'penalty': 'l2'}. Best is trial 3 with value: 0.6810140879132228.
2025/09/27 19:57:31 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '05855408ca954cb7ba2ae9ca93de2e64', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 9 at: http://127.0.0.1:5000/#/experiments/4/runs/9950798ad4104bb5b2ec12e29673e61c
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 19:57:33 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
2025/09/27 20:01:45 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1211.18it/s]

🏃 View run sassy-stag-37 at: http://127.0.0.1:5000/#/experiments/4/runs/05855408ca954cb7ba2ae9ca93de2e64
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 20:01:54 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 20:01:54,949] Trial 10 finished with value: 0.6807703217091026 and parameters: {'solver': 'saga', 'C': 0.07472036614906327, 'max_iter': 1415, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 3 with value: 0.6810140879132228.
2025/09/27 20:01:55 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'c5bd688982d442f49c6c759669c70ec7', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 10 at: http://127.0.0.1:5000/#/experiments/4/runs/06dbe9ffe48b4de597248d912505627b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 20:01:58 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 20:02:00 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1354.50it/s]

🏃 View run caring-bass-359 at: http://127.0.0.1:5000/#/experiments/4/runs/c5bd688982d442f49c6c759669c70ec7
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 20:02:10 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 20:02:10,695] Trial 11 finished with value: 0.6810322180787622 and parameters: {'solver': 'lbfgs', 'C': 0.43185173822276507, 'max_iter': 731, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 11 with value: 0.6810322180787622.
2025/09/27 20:02:11 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'a1cecff264424d67ba124f13724ccba2', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 11 at: http://127.0.0.1:5000/#/experiments/4/runs/6f6e86386d794b8c96160257b2073761
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 20:02:13 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 20:02:15 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1118.18it/s]

🏃 View run gaudy-finch-511 at: http://127.0.0.1:5000/#/experiments/4/runs/a1cecff264424d67ba124f13724ccba2
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 20:02:26 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 20:02:26,382] Trial 12 finished with value: 0.6811064519709382 and parameters: {'solver': 'lbfgs', 'C': 0.3918492159105973, 'max_iter': 1216, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 12 with value: 0.6811064519709382.
2025/09/27 20:02:26 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '23cff536ad4a4b3dafac2988dec5b582', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 12 at: http://127.0.0.1:5000/#/experiments/4/runs/64b4e4a0d25040218878e8a959bd44da
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 20:02:30 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 20:02:32 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1864.85it/s]

🏃 View run unruly-roo-993 at: http://127.0.0.1:5000/#/experiments/4/runs/23cff536ad4a4b3dafac2988dec5b582
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 20:02:44 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 20:02:44,192] Trial 13 finished with value: 0.6810247226974322 and parameters: {'solver': 'lbfgs', 'C': 0.7067155655040259, 'max_iter': 1291, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 12 with value: 0.6811064519709382.
2025/09/27 20:02:44 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '946b30da5522410999cdd77d94a144ad', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 13 at: http://127.0.0.1:5000/#/experiments/4/runs/22dcbd7bd6d64c22ac209c2451fc1298
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 20:02:49 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 20:02:52 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 947.71it/s]

🏃 View run hilarious-moose-823 at: http://127.0.0.1:5000/#/experiments/4/runs/946b30da5522410999cdd77d94a144ad
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 20:03:03 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 20:03:03,479] Trial 14 finished with value: 0.6810223123286032 and parameters: {'solver': 'lbfgs', 'C': 72.47179519147645, 'max_iter': 1226, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 12 with value: 0.6811064519709382.
2025/09/27 20:03:03 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '6f611b2e95b84ff1b214c271ffa4d114', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 14 at: http://127.0.0.1:5000/#/experiments/4/runs/5e218477e7cd484b920359ef1713df05
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 20:03:08 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 20:03:10 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1207.99it/s]

🏃 View run victorious-stoat-711 at: http://127.0.0.1:5000/#/experiments/4/runs/6f611b2e95b84ff1b214c271ffa4d114
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 20:03:21 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 20:03:21,367] Trial 15 finished with value: 0.6810314708188607 and parameters: {'solver': 'lbfgs', 'C': 0.13542717804830243, 'max_iter': 660, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 12 with value: 0.6811064519709382.
2025/09/27 20:03:21 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'efe8d9038aa04b88943e0e22b6333e89', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 15 at: http://127.0.0.1:5000/#/experiments/4/runs/9564c1dd343c45b7b4bf8a68a8d6b906
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 20:03:25 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 20:03:27 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 591.95it/s]

🏃 View run gifted-whale-170 at: http://127.0.0.1:5000/#/experiments/4/runs/efe8d9038aa04b88943e0e22b6333e89
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 20:03:39 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 20:03:39,316] Trial 16 finished with value: 0.6810294659752222 and parameters: {'solver': 'lbfgs', 'C': 1.0678716302894116, 'max_iter': 1182, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 12 with value: 0.6811064519709382.
2025/09/27 20:03:39 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'bfc2f1e98345415aae08e6790c870cbc', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 16 at: http://127.0.0.1:5000/#/experiments/4/runs/e4153050a0524efb8de2e86a52e05cb2
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 20:03:42 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 20:08:09 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1689.50it/s]

🏃 View run rebellious-seal-607 at: http://127.0.0.1:5000/#/experiments/4/runs/bfc2f1e98345415aae08e6790c870cbc
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 20:08:19 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 20:08:20,024] Trial 17 finished with value: 0.6806652223378202 and parameters: {'solver': 'saga', 'C': 0.030937885782643566, 'max_iter': 1433, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 12 with value: 0.6811064519709382.
2025/09/27 20:08:20 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'b6fbc33eb52742b0bf3a67f4e88eb192', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 17 at: http://127.0.0.1:5000/#/experiments/4/runs/afa6f8c8766b4e038f0a9a4fe6a0bff7
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 20:08:22 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 20:08:24 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 2112.24it/s]

🏃 View run loud-gnu-657 at: http://127.0.0.1:5000/#/experiments/4/runs/b6fbc33eb52742b0bf3a67f4e88eb192
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 20:08:35 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 20:08:35,308] Trial 18 finished with value: 0.6738342507459852 and parameters: {'solver': 'lbfgs', 'C': 1.6407555989460931, 'max_iter': 707, 'class_weight': None, 'penalty': 'l2'}. Best is trial 12 with value: 0.6811064519709382.
2025/09/27 20:08:35 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'acc6f4797f964f5d97124366f7b466a2', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 18 at: http://127.0.0.1:5000/#/experiments/4/runs/b57462bd120240049c38d8ec6143e23d
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 20:08:38 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 20:08:40 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1702.63it/s]

🏃 View run sincere-zebra-205 at: http://127.0.0.1:5000/#/experiments/4/runs/acc6f4797f964f5d97124366f7b466a2
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 20:08:48 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 20:08:48,109] Trial 19 finished with value: 0.6810731852359286 and parameters: {'solver': 'lbfgs', 'C': 0.3286768365137037, 'max_iter': 302, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 12 with value: 0.6811064519709382.
2025/09/27 20:08:48 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '65b833121f8d4c57808c1ce40e7e9a73', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 19 at: http://127.0.0.1:5000/#/experiments/4/runs/4fe48d0148404a53a7b6535a1694786e
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 20:08:51 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
2025/09/27 20:09:46 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1671.80it/s]

🏃 View run skillful-vole-496 at: http://127.0.0.1:5000/#/experiments/4/runs/65b833121f8d4c57808c1ce40e7e9a73
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 20:09:54 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 20:09:54,861] Trial 20 finished with value: 0.6780675874436588 and parameters: {'solver': 'saga', 'C': 0.01546248074271159, 'max_iter': 309, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 12 with value: 0.6811064519709382.
2025/09/27 20:09:55 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '19605681831d464b95093b3927e250c7', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 20 at: http://127.0.0.1:5000/#/experiments/4/runs/4c2f029c4ef3489cb0d76eb745e4fed1
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 20:09:57 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 20:09:59 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1454.19it/s]

🏃 View run bold-steed-832 at: http://127.0.0.1:5000/#/experiments/4/runs/19605681831d464b95093b3927e250c7
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 20:10:07 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 20:10:07,151] Trial 21 finished with value: 0.6810976990058714 and parameters: {'solver': 'lbfgs', 'C': 0.20578870702734708, 'max_iter': 626, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 12 with value: 0.6811064519709382.
2025/09/27 20:10:07 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '521dce3a119741209a243e8f5393628b', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 21 at: http://127.0.0.1:5000/#/experiments/4/runs/e57e710218a9480992a3bbd7adbc225c
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 20:10:09 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 20:10:11 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 2012.90it/s]

🏃 View run blushing-robin-131 at: http://127.0.0.1:5000/#/experiments/4/runs/521dce3a119741209a243e8f5393628b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 20:10:19 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 20:10:19,582] Trial 22 finished with value: 0.6811173054653628 and parameters: {'solver': 'lbfgs', 'C': 0.19725257893553938, 'max_iter': 598, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 22 with value: 0.6811173054653628.
2025/09/27 20:10:19 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '87fc05c653314322865e9a6a6719bced', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 22 at: http://127.0.0.1:5000/#/experiments/4/runs/b2781a6d55704c80941367c504866eae
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 20:10:22 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 20:10:24 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 2019.27it/s]

🏃 View run entertaining-ram-790 at: http://127.0.0.1:5000/#/experiments/4/runs/87fc05c653314322865e9a6a6719bced
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 20:10:32 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 20:10:32,596] Trial 23 finished with value: 0.6810542850281736 and parameters: {'solver': 'lbfgs', 'C': 0.17603178466958488, 'max_iter': 600, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 22 with value: 0.6811173054653628.
2025/09/27 20:10:32 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '9b5f86f2f3ff48f3af9d56da773339cd', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 23 at: http://127.0.0.1:5000/#/experiments/4/runs/f9fc4c398af94ed69e06232d89a36286
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 20:10:35 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 20:10:37 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1871.03it/s]

🏃 View run stylish-hare-211 at: http://127.0.0.1:5000/#/experiments/4/runs/9b5f86f2f3ff48f3af9d56da773339cd
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 20:10:46 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 20:10:46,081] Trial 24 finished with value: 0.6810272378649058 and parameters: {'solver': 'lbfgs', 'C': 0.049058829055730564, 'max_iter': 820, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 22 with value: 0.6811173054653628.
2025/09/27 20:10:46 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '0e15f20ca37c4d3f92234b4e44fa3185', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 24 at: http://127.0.0.1:5000/#/experiments/4/runs/79bed4cf449c4a42bcdba6216f8e3397
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 20:10:48 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 20:10:51 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1504.64it/s]

🏃 View run bemused-dog-756 at: http://127.0.0.1:5000/#/experiments/4/runs/0e15f20ca37c4d3f92234b4e44fa3185
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 20:11:01 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 20:11:01,721] Trial 25 finished with value: 0.6810994532440551 and parameters: {'solver': 'lbfgs', 'C': 1.6789366193722508, 'max_iter': 587, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 22 with value: 0.6811173054653628.
2025/09/27 20:11:01 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '72535fc1b0bc440284a9d21e55468538', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 25 at: http://127.0.0.1:5000/#/experiments/4/runs/18ca349190f54a969019fc24cc86dcf9
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 20:11:05 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 20:11:06 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1376.99it/s]

🏃 View run lyrical-rat-217 at: http://127.0.0.1:5000/#/experiments/4/runs/72535fc1b0bc440284a9d21e55468538
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 20:11:16 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 20:11:16,288] Trial 26 finished with value: 0.6739648298573271 and parameters: {'solver': 'lbfgs', 'C': 1.942613405301819, 'max_iter': 1165, 'class_weight': None, 'penalty': 'l2'}. Best is trial 22 with value: 0.6811173054653628.
2025/09/27 20:11:16 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '7cf2bb93ab0241b686b47af28897968b', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 26 at: http://127.0.0.1:5000/#/experiments/4/runs/cb3b336183f94ba1b843c0a74a83aac0
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 20:11:19 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 20:11:21 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1213.08it/s]

🏃 View run youthful-rook-780 at: http://127.0.0.1:5000/#/experiments/4/runs/7cf2bb93ab0241b686b47af28897968b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 20:11:32 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 20:11:32,438] Trial 27 finished with value: 0.6809444742743408 and parameters: {'solver': 'lbfgs', 'C': 0.019765987243464195, 'max_iter': 540, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 22 with value: 0.6811173054653628.
2025/09/27 20:11:32 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '263b09b6482c42e9bac48c9aaa04e7b2', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 27 at: http://127.0.0.1:5000/#/experiments/4/runs/f805963d20984b92865c14b7a663fac1
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 20:11:36 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 20:14:29 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1369.73it/s]

🏃 View run mysterious-snail-873 at: http://127.0.0.1:5000/#/experiments/4/runs/263b09b6482c42e9bac48c9aaa04e7b2
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 20:14:39 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 20:14:39,700] Trial 28 finished with value: 0.6797544036470256 and parameters: {'solver': 'saga', 'C': 0.007022550372190417, 'max_iter': 1075, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 22 with value: 0.6811173054653628.
2025/09/27 20:14:39 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'be63df8453014eee93df0e30a19af0f2', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 28 at: http://127.0.0.1:5000/#/experiments/4/runs/d2f2b957b8fb4215aee08769bd06a9d3
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 20:14:43 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 20:14:45 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1316.24it/s]

🏃 View run funny-sloth-98 at: http://127.0.0.1:5000/#/experiments/4/runs/be63df8453014eee93df0e30a19af0f2
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 20:14:55 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 20:14:55,477] Trial 29 finished with value: 0.6809511768311411 and parameters: {'solver': 'lbfgs', 'C': 1.9405613880346864, 'max_iter': 927, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 22 with value: 0.6811173054653628.

🏃 View run 29 at: http://127.0.0.1:5000/#/experiments/4/runs/32418668422c4ed68881ec3c867c5379
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

Optimization complete!
Best roc_auc: 0.6811
Best parameters: {'solver': 'lbfgs', 'C': 0.19725257893553938, 'max_iter': 598, 'class_weight': 'balanced', 'penalty': 'l2'}

2025/09/27 20:14:59 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 20:15:01 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1143.08it/s]
2025/09/27 20:15:14 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 20:15:16 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 20:15:19 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 20:15:21 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."