In [1]:
import json
import random
from datetime import datetime, timedelta
from ucimlrepo import fetch_ucirepo, list_available_datasets
import numpy as np
import pandas as pd
from etl import UserGenerator
from feature_engineer import FeatureEngineer
from sklearn.linear_model import LogisticRegression
from train_mlflow import TrainMlflow
from train_mlflow_advance import TrainOptuna

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

# ETL

In [2]:
user_generator = UserGenerator(n_samples=25000)

In [3]:
ds = user_generator.create_dataset()
print(type(ds), isinstance(ds, tuple))

<class 'pandas.core.frame.DataFrame'> False

In [4]:
ds

,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...
541904,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

In [5]:
ds = user_generator.run_etl()

In [6]:
ds.info

<bound method DataFrame.info of                                 Description  Quantity         InvoiceDate  \
0        WHITE HANGING HEART T-LIGHT HOLDER         6 2010-12-01 08:26:00
1                       WHITE METAL LANTERN         6 2010-12-01 08:26:00
2            CREAM CUPID HEARTS COAT HANGER         8 2010-12-01 08:26:00
3       KNITTED UNION FLAG HOT WATER BOTTLE         6 2010-12-01 08:26:00
4            RED WOOLLY HOTTIE WHITE HEART.         6 2010-12-01 08:26:00
...                                     ...       ...                 ...
541904          PACK OF 20 SPACEBOY NAPKINS        12 2011-12-09 12:50:00
541905         CHILDREN'S APRON DOLLY GIRL          6 2011-12-09 12:50:00
541906        CHILDRENS CUTLERY DOLLY GIRL          4 2011-12-09 12:50:00
541907      CHILDRENS CUTLERY CIRCUS PARADE         4 2011-12-09 12:50:00
541908        BAKING SET 9 PIECE RETROSPOT          3 2011-12-09 12:50:00

        UnitPrice  CustomerID         Country
0            2.55       17850  United Kingdom
1            3.39       17850  United Kingdom
2            2.75       17850  United Kingdom
3            3.39       17850  United Kingdom
4            3.39       17850  United Kingdom
...           ...         ...             ...
541904       0.85       12680          France
541905       2.10       12680          France
541906       4.15       12680          France
541907       4.15       12680          France
541908       4.95       12680          France

[397884 rows x 6 columns]>

In [7]:
ds.describe().T

,count,mean,min,25%,50%,75%,max,std
Quantity,397884.0,12.988238,1.0,2.0,6.0,12.0,80995.0,179.331775
InvoiceDate,397884,2011-07-10 23:41:23.511023360,2010-12-01 08:26:00,2011-04-07 11:12:00,2011-07-31 14:39:00,2011-10-20 14:33:00,2011-12-09 12:50:00,NaN
UnitPrice,397884.0,3.116488,0.001,1.25,1.95,3.75,8142.75,22.097877
CustomerID,397884.0,15294.423453,12346.0,13969.0,15159.0,16795.0,18287.0,1713.14156

In [8]:
ds.columns

Index(['Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID',
       'Country'],
      dtype='object')

In [9]:
# Información base
print("Fecha mínima:", ds["InvoiceDate"].min())
print("Fecha máxima:", ds["InvoiceDate"].max())
print("Clientes únicos:", ds["CustomerID"].nunique())
print("Productos únicos:", ds["Description"].nunique())
print("Países:", ds["Country"].nunique())
print(f"Rango de fechas: {ds['InvoiceDate'].min().date()} → {ds['InvoiceDate'].max().date()}")

Fecha mínima: 2010-12-01 08:26:00
Fecha máxima: 2011-12-09 12:50:00
Clientes únicos: 4338
Productos únicos: 3877
Países: 37
Rango de fechas: 2010-12-01 → 2011-12-09

# Feature Engineering

In [10]:
feature_engineer = FeatureEngineer(ds)

In [11]:
df_engineered = feature_engineer.run()

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\src\app\train\feature_engineer.py:52: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(self.historial_compra)   # <-- ahora acepta g

In [12]:
df_engineered

,Description,InvoiceDate,Country,Quantity,Revenue,UnitPrice,CustomerID,n_past_invoices,prev_date,recency_days,spend_prior,qty_prior,avg_ticket_prior,avg_qty_per_invoice_prior,next_date,days_to_next,y_repurchase_30d
0,MEDIUM CERAMIC TOP STORAGE JAR,2011-01-18 10:01:00,United Kingdom,74215,77183.60,1.04,12346,0,NaT,9999,0.00,0,0.000000,0.000000,NaT,NaN,0
1,3D DOG PICTURE PLAYING CARDS,2010-12-07 14:57:00,Iceland,24,70.80,2.95,12347,0,NaT,9999,0.00,0,0.000000,0.000000,2010-12-07 14:57:00,0.0,1
2,AIRLINE BAG VINTAGE JET SET BROWN,2010-12-07 14:57:00,Iceland,4,17.00,4.25,12347,1,2010-12-07 14:57:00,0,70.80,24,70.800000,24.000000,2010-12-07 14:57:00,0.0,1
3,ALARM CLOCK BAKELIKE CHOCOLATE,2010-12-07 14:57:00,Iceland,4,15.00,3.75,12347,2,2010-12-07 14:57:00,0,87.80,28,43.900000,14.000000,2010-12-07 14:57:00,0.0,1
4,ALARM CLOCK BAKELIKE GREEN,2010-12-07 14:57:00,Iceland,4,15.00,3.75,12347,3,2010-12-07 14:57:00,0,102.80,32,34.266667,10.666667,2010-12-07 14:57:00,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
387655,SWISS CHALET TREE DECORATION,2011-10-12 10:23:00,United Kingdom,24,6.96,0.29,18287,63,2011-10-12 10:23:00,0,1739.84,1442,27.616508,22.888889,2011-10-12 10:23:00,0.0,1
387656,TREE T-LIGHT HOLDER WILLIE WINKIE,2011-10-12 10:23:00,United Kingdom,12,19.80,1.65,18287,64,2011-10-12 10:23:00,0,1746.80,1466,27.293750,22.906250,2011-10-28 09:29:00,15.0,1
387657,PAINTED METAL STAR WITH HOLLY BELLS,2011-10-28 09:29:00,United Kingdom,48,18.72,0.39,18287,65,2011-10-12 10:23:00,15,1766.60,1478,27.178462,22.738462,2011-10-28 09:29:00,0.0,1
387658,SET OF 3 WOODEN SLEIGH DECORATIONS,2011-10-28 09:29:00,United Kingdom,36,45.00,1.25,18287,66,2011-10-28 09:29:00,0,1785.32,1526,27.050303,23.121212,2011-10-28 09:29:00,0.0,1
387659,SWISS CHALET TREE DECORATION,2011-10-28 09:29:00,United Kingdom,24,6.96,0.29,18287,67,2011-10-28 09:29:00,0,1830.32,1562,27.318209,23.313433,NaT,NaN,0

# Modelando con MLFlow

In [13]:
import mlflow


experiment_name = "recompra-LogReg"
mlflow.set_tracking_uri("http://127.0.0.1:5000")
mlflow.set_experiment(experiment_name)

# Enable autologging for sklearn models
mlflow.sklearn.autolog(
    log_input_examples=True,
    log_model_signatures=True,
    log_models=True,
    disable=False,
    exclusive=False,
    disable_for_unsupported_versions=False,
    silent=False,
    max_tuning_runs=5
)

In [14]:
num_feats = [
    'recency_days','n_past_invoices','spend_prior','qty_prior',
    'avg_ticket_prior','avg_qty_per_invoice_prior','UnitPrice','Quantity','Revenue'
]
cat_feats = ['Country']

In [15]:


model = LogisticRegression(max_iter=500)

# 3) Instancia y entrena
trainer = TrainMlflow(
    df=df_engineered,
    numeric_features=num_feats,
    categorical_features=cat_feats,
    target_column='y_repurchase_30d',
    model=model,
    mlflow_setup={"tracking_uri": "file:./mlruns", "experiment_name": "OnlineRetail"}
)

pipeline, run_id = trainer.train()
trainer.pipeline = pipeline                  # <- necesario para save_model()
trainer.save_model("models/model.pkl")       # ✅ Modelo guardado en models/model.pkl

Rango total: 2010-12-01 08:26:00 → 2011-12-09 12:50:00 | cutoff: 2011-11-09 12:50:00
train_end: 2011-09-01 00:00:00
train: 218546 | test: 102095
pos_rate train=0.972 | test=0.979

2025/09/20 17:12:11 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/20 17:12:13 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 742.19it/s]
2025/09/20 17:12:30 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/20 17:12:32 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."

MLflow Run ID: d9d7c79ebdbd4e4ea2884c0b81e6d428
Tracking URI: http://127.0.0.1:5000
Train Accuracy: 0.9720
Test Accuracy: 0.9786
🏃 View run rare-grub-51 at: http://127.0.0.1:5000/#/experiments/1/runs/d9d7c79ebdbd4e4ea2884c0b81e6d428
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1
✅ Modelo guardado en models/model.pkl

'models/model.pkl'

In [16]:
mlflow.set_experiment("recompra-optuna")

params = {
            'solver': ('categorical', ['lbfgs', 'liblinear', 'saga']),
            'C':      ('float', 1e-3, 1e2, True),
            'max_iter': ('int', 300, 1500),
            'class_weight': ('categorical', [None, 'balanced']),
            # solver-specific penalties are tricky to encode generically—start simple with l2
            'penalty': ('categorical', ['l2']),
}

trainer = TrainOptuna(
    df=df_engineered,
    numeric_features=num_feats,
    categorical_features=cat_feats,
    target_column='y_repurchase_30d',
    model_class=LogisticRegression,
    model_params={},                 
    n_trials=30,                     
    optimization_metric='roc_auc',   
    param_distributions=params,
)

best_pipeline, best_run_id, study = trainer.train()   # runs Optuna + logs to MLflow
trainer.save_model("models/modeloptuna.pkl")

[I 2025-09-20 17:12:33,051] A new study created in memory with name: optuna_LogisticRegression
c:\Users\gabri\OneDrive\ProyectoFinalMLOps\src\app\train\train_mlflow_advance.py:247: ExperimentalWarning: MLflowCallback is experimental (supported from v1.4.0). The interface can change in the future.
  mlflow_callback = MLflowCallback(
2025/09/20 17:12:33 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '8a74c9e5d24f48379717c90d19ab9dfe', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

Rango total: 2010-12-01 08:26:00 → 2011-12-09 12:50:00 | cutoff: 2011-11-09 12:50:00
train_end: 2011-09-01 00:00:00
train: 218546 | test: 102095
pos_rate train=0.972 | test=0.979
Starting Optuna optimization with 30 trials...
Optimizing for: roc_auc
Model type: LogisticRegression

2025/09/20 17:12:35 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/20 17:13:46 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1462.96it/s]

🏃 View run treasured-boar-803 at: http://127.0.0.1:5000/#/experiments/2/runs/8a74c9e5d24f48379717c90d19ab9dfe
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/20 17:13:55 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-20 17:13:55,588] Trial 0 finished with value: 0.6919473254214179 and parameters: {'solver': 'saga', 'C': 0.0034996915884624754, 'max_iter': 865, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 0 with value: 0.6919473254214179.
2025/09/20 17:13:55 INFO mlflow.tracking.fluent: Experiment with name 'optuna_LogisticRegression' does not exist. Creating a new experiment.
2025/09/20 17:13:55 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '6cb493b8f4ad4b4cac97a1c356b7b9a4', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 0 at: http://127.0.0.1:5000/#/experiments/3/runs/23c172ff91b34a128cc4daa5e1e19a70
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

2025/09/20 17:13:59 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/20 17:14:00 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1104.51it/s]

🏃 View run treasured-panda-209 at: http://127.0.0.1:5000/#/experiments/3/runs/6cb493b8f4ad4b4cac97a1c356b7b9a4
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/20 17:14:10 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-20 17:14:10,302] Trial 1 finished with value: 0.680928170881088 and parameters: {'solver': 'lbfgs', 'C': 0.0016629284020218097, 'max_iter': 847, 'class_weight': None, 'penalty': 'l2'}. Best is trial 0 with value: 0.6919473254214179.
2025/09/20 17:14:10 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'badfef336d79497a847ee1743cab0edf', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 1 at: http://127.0.0.1:5000/#/experiments/3/runs/238e5c6a0601488097a10948fa1480f8
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

2025/09/20 17:14:13 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
2025/09/20 17:17:37 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 935.27it/s]

🏃 View run righteous-sponge-688 at: http://127.0.0.1:5000/#/experiments/3/runs/badfef336d79497a847ee1743cab0edf
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/20 17:17:47 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-20 17:17:47,654] Trial 2 finished with value: 0.6911927720645198 and parameters: {'solver': 'saga', 'C': 1.6141338612984224, 'max_iter': 1082, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 0 with value: 0.6919473254214179.
2025/09/20 17:17:47 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '46fbf7558f9b441298c8bf2ac3984f15', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 2 at: http://127.0.0.1:5000/#/experiments/3/runs/a732d32f66794da39d884d60a4c694da
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

2025/09/20 17:17:51 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/20 17:17:55 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 698.05it/s]

🏃 View run glamorous-worm-285 at: http://127.0.0.1:5000/#/experiments/3/runs/46fbf7558f9b441298c8bf2ac3984f15
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/20 17:18:07 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-20 17:18:07,821] Trial 3 finished with value: 0.6770202088436222 and parameters: {'solver': 'liblinear', 'C': 5.8609039411451, 'max_iter': 923, 'class_weight': None, 'penalty': 'l2'}. Best is trial 0 with value: 0.6919473254214179.
2025/09/20 17:18:08 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '760e20df7bc443219ebce92785c3bc8a', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 3 at: http://127.0.0.1:5000/#/experiments/3/runs/17d942c6d2d64ba6b87d1706f27e0279
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

2025/09/20 17:18:12 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/20 17:18:14 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1462.45it/s]

🏃 View run dazzling-shrimp-842 at: http://127.0.0.1:5000/#/experiments/3/runs/760e20df7bc443219ebce92785c3bc8a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/20 17:18:22 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-20 17:18:22,979] Trial 4 finished with value: 0.69085624389436 and parameters: {'solver': 'liblinear', 'C': 0.6458152864541605, 'max_iter': 715, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 0 with value: 0.6919473254214179.
2025/09/20 17:18:23 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'a117ef1c83034338a74780aca369f307', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 4 at: http://127.0.0.1:5000/#/experiments/3/runs/9e0c688232784c618d313a2ab5c7776d
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

2025/09/20 17:18:25 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/20 17:18:26 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 2050.86it/s]

🏃 View run enchanting-ox-639 at: http://127.0.0.1:5000/#/experiments/3/runs/a117ef1c83034338a74780aca369f307
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/20 17:18:35 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-20 17:18:35,100] Trial 5 finished with value: 0.6921818530295243 and parameters: {'solver': 'lbfgs', 'C': 0.0026136157414133536, 'max_iter': 849, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 5 with value: 0.6921818530295243.
2025/09/20 17:18:35 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '9bb78cbc2c124c54b5e1f8561ab04c2e', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 5 at: http://127.0.0.1:5000/#/experiments/3/runs/fb465176462a4eb2bcfd0552b848c011
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

2025/09/20 17:18:37 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
2025/09/20 17:21:49 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1297.46it/s]

🏃 View run secretive-robin-717 at: http://127.0.0.1:5000/#/experiments/3/runs/9bb78cbc2c124c54b5e1f8561ab04c2e
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/20 17:21:59 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-20 17:21:59,403] Trial 6 finished with value: 0.6751836312178123 and parameters: {'solver': 'saga', 'C': 2.2039551197963565, 'max_iter': 973, 'class_weight': None, 'penalty': 'l2'}. Best is trial 5 with value: 0.6921818530295243.
2025/09/20 17:21:59 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'ed478e55a7c44b12bbd70a0265ab3a51', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 6 at: http://127.0.0.1:5000/#/experiments/3/runs/7d2d4439367f470cbb37e68085d1f2a2
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

2025/09/20 17:22:02 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
2025/09/20 17:25:45 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1244.71it/s]

🏃 View run resilient-sheep-136 at: http://127.0.0.1:5000/#/experiments/3/runs/ed478e55a7c44b12bbd70a0265ab3a51
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/20 17:25:53 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-20 17:25:53,830] Trial 7 finished with value: 0.69114214478326 and parameters: {'solver': 'saga', 'C': 84.44262788518515, 'max_iter': 1425, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 5 with value: 0.6921818530295243.
2025/09/20 17:25:54 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'beaabfade43e4c3cbac409d585461760', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 7 at: http://127.0.0.1:5000/#/experiments/3/runs/4b8c1858aa1f4452b6a776280280f0d6
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

2025/09/20 17:25:56 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/20 17:25:58 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1874.13it/s]

🏃 View run able-foal-683 at: http://127.0.0.1:5000/#/experiments/3/runs/beaabfade43e4c3cbac409d585461760
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/20 17:26:05 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-20 17:26:05,721] Trial 8 finished with value: 0.6916263625544188 and parameters: {'solver': 'lbfgs', 'C': 0.008111108577416261, 'max_iter': 837, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 5 with value: 0.6921818530295243.
2025/09/20 17:26:05 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'ccba439c52754e1fa6528aae90938721', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 8 at: http://127.0.0.1:5000/#/experiments/3/runs/78801445b0b745edbf0a6baa3108fd2a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

2025/09/20 17:26:08 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/20 17:26:09 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1969.55it/s]

🏃 View run adaptable-shrew-29 at: http://127.0.0.1:5000/#/experiments/3/runs/ccba439c52754e1fa6528aae90938721
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/20 17:26:18 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-20 17:26:18,455] Trial 9 finished with value: 0.6775024311804446 and parameters: {'solver': 'lbfgs', 'C': 0.6597666851844416, 'max_iter': 1327, 'class_weight': None, 'penalty': 'l2'}. Best is trial 5 with value: 0.6921818530295243.
2025/09/20 17:26:18 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '446587ee548446b08498a40f6ee780b3', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 9 at: http://127.0.0.1:5000/#/experiments/3/runs/fb7936f7a24742f589898590d1c4fbc6
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

2025/09/20 17:26:21 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/20 17:26:23 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 812.40it/s]

🏃 View run whimsical-ram-507 at: http://127.0.0.1:5000/#/experiments/3/runs/446587ee548446b08498a40f6ee780b3
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/20 17:26:34 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-20 17:26:34,514] Trial 10 finished with value: 0.6911251744380321 and parameters: {'solver': 'lbfgs', 'C': 0.03413761351804133, 'max_iter': 439, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 5 with value: 0.6921818530295243.
2025/09/20 17:26:34 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'c9aa26c9a11442cdbbca54318b8180e6', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 10 at: http://127.0.0.1:5000/#/experiments/3/runs/ff3a19a4769c4293a6261834d53fb41f
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

2025/09/20 17:26:39 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
2025/09/20 17:29:38 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1285.81it/s]

🏃 View run kindly-doe-67 at: http://127.0.0.1:5000/#/experiments/3/runs/c9aa26c9a11442cdbbca54318b8180e6
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/20 17:29:51 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-20 17:29:51,900] Trial 11 finished with value: 0.6913389101695554 and parameters: {'solver': 'saga', 'C': 0.0387653431145907, 'max_iter': 570, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 5 with value: 0.6921818530295243.
2025/09/20 17:29:52 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'ed2abe0a88834ab79be64f101091e8d3', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 11 at: http://127.0.0.1:5000/#/experiments/3/runs/9685a2f9db5347f6a8f5b9cd8991260c
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

2025/09/20 17:29:56 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/20 17:30:58 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 747.08it/s]

🏃 View run abrasive-stoat-812 at: http://127.0.0.1:5000/#/experiments/3/runs/ed2abe0a88834ab79be64f101091e8d3
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/20 17:31:10 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-20 17:31:10,654] Trial 12 finished with value: 0.6930241139635387 and parameters: {'solver': 'saga', 'C': 0.0011186283663842953, 'max_iter': 1133, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 12 with value: 0.6930241139635387.
2025/09/20 17:31:11 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '94107b928f304729adfd77780fc3d164', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 12 at: http://127.0.0.1:5000/#/experiments/3/runs/12184d69941549119f8b6ecc4546c152
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

2025/09/20 17:31:15 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/20 17:31:17 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 889.62it/s]

🏃 View run omniscient-wolf-543 at: http://127.0.0.1:5000/#/experiments/3/runs/94107b928f304729adfd77780fc3d164
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/20 17:31:27 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-20 17:31:27,703] Trial 13 finished with value: 0.6931183112789328 and parameters: {'solver': 'lbfgs', 'C': 0.0010582495531749523, 'max_iter': 1184, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 13 with value: 0.6931183112789328.
2025/09/20 17:31:28 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '19f362b830fb4f3faf8751a21c7d2750', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 13 at: http://127.0.0.1:5000/#/experiments/3/runs/4487cf166be64bd78a977084ab85f742
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

2025/09/20 17:31:32 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/20 17:31:34 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1452.75it/s]

🏃 View run melodic-snail-100 at: http://127.0.0.1:5000/#/experiments/3/runs/19f362b830fb4f3faf8751a21c7d2750
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/20 17:31:44 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-20 17:31:44,768] Trial 14 finished with value: 0.6912938481363532 and parameters: {'solver': 'liblinear', 'C': 0.023387140887984555, 'max_iter': 1197, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 13 with value: 0.6931183112789328.
2025/09/20 17:31:45 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '48ef288cf3ae48caad11cff0e3385965', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 14 at: http://127.0.0.1:5000/#/experiments/3/runs/e179f121910c4dfd8585a6a9309f1835
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

2025/09/20 17:31:49 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
2025/09/20 17:37:48 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1331.40it/s]

🏃 View run useful-fox-670 at: http://127.0.0.1:5000/#/experiments/3/runs/48ef288cf3ae48caad11cff0e3385965
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/20 17:37:56 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-20 17:37:56,184] Trial 15 finished with value: 0.6912094540786395 and parameters: {'solver': 'saga', 'C': 0.12136972075479864, 'max_iter': 1194, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 13 with value: 0.6931183112789328.
2025/09/20 17:37:56 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'd43b4f6050d6455b8709af240790f298', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 15 at: http://127.0.0.1:5000/#/experiments/3/runs/9bdac8dbb9ec4615a742ef3ba479a94d
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

2025/09/20 17:38:00 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/20 17:38:01 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 884.55it/s]

🏃 View run welcoming-conch-331 at: http://127.0.0.1:5000/#/experiments/3/runs/d43b4f6050d6455b8709af240790f298
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/20 17:38:12 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-20 17:38:13,017] Trial 16 finished with value: 0.6931157712191696 and parameters: {'solver': 'lbfgs', 'C': 0.001059849363152738, 'max_iter': 1493, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 13 with value: 0.6931183112789328.
2025/09/20 17:38:13 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '83b1e18e13e84ba1acfb7ef869838b11', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 16 at: http://127.0.0.1:5000/#/experiments/3/runs/0a10f27d6d144728b3429dadbfdd6beb
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

2025/09/20 17:38:17 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/20 17:38:19 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1012.24it/s]

🏃 View run dashing-calf-398 at: http://127.0.0.1:5000/#/experiments/3/runs/83b1e18e13e84ba1acfb7ef869838b11
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/20 17:38:30 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-20 17:38:30,188] Trial 17 finished with value: 0.6915669434626999 and parameters: {'solver': 'lbfgs', 'C': 0.010979261230249924, 'max_iter': 1496, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 13 with value: 0.6931183112789328.
2025/09/20 17:38:30 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '4dcd1b88fce1447c8cab48e17f8c612e', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 17 at: http://127.0.0.1:5000/#/experiments/3/runs/0e9adcca98854b889edfc5b121b9c0ea
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

2025/09/20 17:38:35 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/20 17:38:36 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 739.21it/s]

🏃 View run capricious-stork-490 at: http://127.0.0.1:5000/#/experiments/3/runs/4dcd1b88fce1447c8cab48e17f8c612e
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/20 17:38:47 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-20 17:38:47,193] Trial 18 finished with value: 0.6772767914931669 and parameters: {'solver': 'lbfgs', 'C': 0.0895971977456861, 'max_iter': 1297, 'class_weight': None, 'penalty': 'l2'}. Best is trial 13 with value: 0.6931183112789328.
2025/09/20 17:38:47 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '26644384562f41a9ab01555be536b097', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 18 at: http://127.0.0.1:5000/#/experiments/3/runs/0265b1bba1ca4a74b44295b53daaeae2
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

2025/09/20 17:38:51 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/20 17:38:53 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1173.89it/s]

🏃 View run bustling-grub-973 at: http://127.0.0.1:5000/#/experiments/3/runs/26644384562f41a9ab01555be536b097
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/20 17:39:07 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-20 17:39:07,301] Trial 19 finished with value: 0.6917468712276108 and parameters: {'solver': 'lbfgs', 'C': 0.007728769113719425, 'max_iter': 1353, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 13 with value: 0.6931183112789328.
2025/09/20 17:39:07 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '93d84caea52b4da8a89089033e6dafdf', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 19 at: http://127.0.0.1:5000/#/experiments/3/runs/f52866d3b9584232983bfade866424c8
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

2025/09/20 17:39:11 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/20 17:39:15 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 964.49it/s]

🏃 View run selective-flea-144 at: http://127.0.0.1:5000/#/experiments/3/runs/93d84caea52b4da8a89089033e6dafdf
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/20 17:39:25 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-20 17:39:25,539] Trial 20 finished with value: 0.6909199055723858 and parameters: {'solver': 'lbfgs', 'C': 43.33211243414857, 'max_iter': 1490, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 13 with value: 0.6931183112789328.
2025/09/20 17:39:25 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '2b22b85e0af34b018964d7358c16339a', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 20 at: http://127.0.0.1:5000/#/experiments/3/runs/4098f6455f654bb5b83f98e15f8a2e61
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

2025/09/20 17:39:30 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/20 17:39:31 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 779.22it/s]

🏃 View run funny-rat-77 at: http://127.0.0.1:5000/#/experiments/3/runs/2b22b85e0af34b018964d7358c16339a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/20 17:39:42 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-20 17:39:42,479] Trial 21 finished with value: 0.6930886131747838 and parameters: {'solver': 'lbfgs', 'C': 0.0010778688914307507, 'max_iter': 1096, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 13 with value: 0.6931183112789328.
2025/09/20 17:39:42 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'ef196289f32e4e3886fd3dc94a491a61', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 21 at: http://127.0.0.1:5000/#/experiments/3/runs/68e02c412e5248428399a0a3f601f063
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

2025/09/20 17:39:47 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/20 17:39:48 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 739.18it/s]

🏃 View run caring-sponge-461 at: http://127.0.0.1:5000/#/experiments/3/runs/ef196289f32e4e3886fd3dc94a491a61
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/20 17:39:59 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-20 17:39:59,785] Trial 22 finished with value: 0.6928283234109903 and parameters: {'solver': 'lbfgs', 'C': 0.0012938773571612814, 'max_iter': 1061, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 13 with value: 0.6931183112789328.
2025/09/20 17:40:00 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'b7dcfe0904e740e09c5bf9a4d9025697', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 22 at: http://127.0.0.1:5000/#/experiments/3/runs/9c61d5f01f924eb199d2fbe31b3fc642
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

2025/09/20 17:40:04 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/20 17:40:06 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1718.88it/s]

🏃 View run able-rook-786 at: http://127.0.0.1:5000/#/experiments/3/runs/b7dcfe0904e740e09c5bf9a4d9025697
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/20 17:40:17 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-20 17:40:17,249] Trial 23 finished with value: 0.6918734989276554 and parameters: {'solver': 'lbfgs', 'C': 0.004194090663102719, 'max_iter': 1243, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 13 with value: 0.6931183112789328.
2025/09/20 17:40:17 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '7456f20f2a674943b2f3085610ab57b9', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 23 at: http://127.0.0.1:5000/#/experiments/3/runs/552163be604d44efa80ad5a1606aa774
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

2025/09/20 17:40:22 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/20 17:40:24 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 663.42it/s]

🏃 View run puzzled-bat-346 at: http://127.0.0.1:5000/#/experiments/3/runs/7456f20f2a674943b2f3085610ab57b9
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/20 17:40:34 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-20 17:40:35,042] Trial 24 finished with value: 0.6918524095665954 and parameters: {'solver': 'lbfgs', 'C': 0.004334014518946429, 'max_iter': 1390, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 13 with value: 0.6931183112789328.
2025/09/20 17:40:35 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '10a8a5d1e36d4777a5570153c2bf4431', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 24 at: http://127.0.0.1:5000/#/experiments/3/runs/91c2836f45584357a452566b46fd717a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

2025/09/20 17:40:39 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/20 17:40:41 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1378.73it/s]

🏃 View run nebulous-ox-594 at: http://127.0.0.1:5000/#/experiments/3/runs/10a8a5d1e36d4777a5570153c2bf4431
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/20 17:40:51 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-20 17:40:51,973] Trial 25 finished with value: 0.6930019902718365 and parameters: {'solver': 'lbfgs', 'C': 0.0011517895000162964, 'max_iter': 1020, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 13 with value: 0.6931183112789328.
2025/09/20 17:40:52 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'e68f0f285c7c496988c098f1c5419a6f', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 25 at: http://127.0.0.1:5000/#/experiments/3/runs/d84f268dfcea4bf68e4f20766cbd7476
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

2025/09/20 17:40:56 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/20 17:40:58 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1395.11it/s]

🏃 View run clean-lark-774 at: http://127.0.0.1:5000/#/experiments/3/runs/e68f0f285c7c496988c098f1c5419a6f
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/20 17:41:09 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-20 17:41:09,135] Trial 26 finished with value: 0.6768287798711714 and parameters: {'solver': 'liblinear', 'C': 0.015611132012511172, 'max_iter': 712, 'class_weight': None, 'penalty': 'l2'}. Best is trial 13 with value: 0.6931183112789328.
2025/09/20 17:41:09 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '6caf28e7e75443d0938ce831a331547c', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 26 at: http://127.0.0.1:5000/#/experiments/3/runs/a4946e66f09646d98a6c1ef2834b9a6e
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

2025/09/20 17:41:13 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/20 17:41:15 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1008.25it/s]

🏃 View run respected-donkey-254 at: http://127.0.0.1:5000/#/experiments/3/runs/6caf28e7e75443d0938ce831a331547c
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/20 17:41:26 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-20 17:41:26,198] Trial 27 finished with value: 0.6920763833408035 and parameters: {'solver': 'lbfgs', 'C': 0.003056762849205581, 'max_iter': 1162, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 13 with value: 0.6931183112789328.
2025/09/20 17:41:26 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '6b05906e54cf4c6cbc1c731ab13eae25', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 27 at: http://127.0.0.1:5000/#/experiments/3/runs/e87d445836b44471813ef775124e21a8
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

2025/09/20 17:41:31 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/20 17:41:33 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1587.29it/s]

🏃 View run upset-rat-294 at: http://127.0.0.1:5000/#/experiments/3/runs/6b05906e54cf4c6cbc1c731ab13eae25
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/20 17:41:44 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-20 17:41:44,553] Trial 28 finished with value: 0.6911442637880714 and parameters: {'solver': 'lbfgs', 'C': 0.09490031268106074, 'max_iter': 1266, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 13 with value: 0.6931183112789328.
2025/09/20 17:41:44 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'ddc08926e69f43d7b42547312211ce39', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 28 at: http://127.0.0.1:5000/#/experiments/3/runs/db2252ce964c4061a28bfa2ec0eae115
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

2025/09/20 17:41:48 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/20 17:41:50 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1016.84it/s]

🏃 View run rumbling-wasp-186 at: http://127.0.0.1:5000/#/experiments/3/runs/ddc08926e69f43d7b42547312211ce39
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/20 17:42:01 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-20 17:42:01,575] Trial 29 finished with value: 0.6917956449517461 and parameters: {'solver': 'lbfgs', 'C': 0.005519916754260269, 'max_iter': 1420, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 13 with value: 0.6931183112789328.

🏃 View run 29 at: http://127.0.0.1:5000/#/experiments/3/runs/8ca44392744a4103847391f843a871cf
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

Optimization complete!
Best roc_auc: 0.6931
Best parameters: {'solver': 'lbfgs', 'C': 0.0010582495531749523, 'max_iter': 1184, 'class_weight': 'balanced', 'penalty': 'l2'}

2025/09/20 17:42:06 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/20 17:42:08 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1146.43it/s]
2025/09/20 17:42:21 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/20 17:42:23 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
  warnings.warn(
2025/09/20 17:42:28 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1595.31it/s]
2025/09/20 17:42:32 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."

Best Model MLflow Run ID: 110275231d034c27a158c01dc387dfec
Tracking URI: http://127.0.0.1:5000
Train Accuracy: 0.4479
Test Accuracy: 0.6210
🏃 View run best_model_LogisticRegression at: http://127.0.0.1:5000/#/experiments/3/runs/110275231d034c27a158c01dc387dfec
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3
✅ Modelo guardado en models/modeloptuna.pkl

'models/modeloptuna.pkl'