In [11]:
import json
import random
from datetime import datetime, timedelta
from ucimlrepo import fetch_ucirepo, list_available_datasets
import numpy as np
import pandas as pd
from etl import UserGenerator
from feature_engineer import FeatureEngineer
from sklearn.linear_model import LogisticRegression
from train_mlflow import TrainMlflow
from train_mlflow_advance import TrainOptuna

# ETL

In [12]:
user_generator = UserGenerator(n_samples=25000)

In [13]:
ds = user_generator.create_dataset()
print(type(ds), isinstance(ds, tuple))

<class 'pandas.core.frame.DataFrame'> False

In [14]:
ds

,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...
541904,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

In [15]:
ds = user_generator.run_etl()

In [16]:
ds.info

<bound method DataFrame.info of                                 Description  Quantity      InvoiceDate  \
0        WHITE HANGING HEART T-LIGHT HOLDER         6   12/1/2010 8:26
1                       WHITE METAL LANTERN         6   12/1/2010 8:26
2            CREAM CUPID HEARTS COAT HANGER         8   12/1/2010 8:26
3       KNITTED UNION FLAG HOT WATER BOTTLE         6   12/1/2010 8:26
4            RED WOOLLY HOTTIE WHITE HEART.         6   12/1/2010 8:26
...                                     ...       ...              ...
541904          PACK OF 20 SPACEBOY NAPKINS        12  12/9/2011 12:50
541905         CHILDREN'S APRON DOLLY GIRL          6  12/9/2011 12:50
541906        CHILDRENS CUTLERY DOLLY GIRL          4  12/9/2011 12:50
541907      CHILDRENS CUTLERY CIRCUS PARADE         4  12/9/2011 12:50
541908        BAKING SET 9 PIECE RETROSPOT          3  12/9/2011 12:50

        UnitPrice  CustomerID         Country
0            2.55     17850.0  United Kingdom
1            3.39     17850.0  United Kingdom
2            2.75     17850.0  United Kingdom
3            3.39     17850.0  United Kingdom
4            3.39     17850.0  United Kingdom
...           ...         ...             ...
541904       0.85     12680.0          France
541905       2.10     12680.0          France
541906       4.15     12680.0          France
541907       4.15     12680.0          France
541908       4.95     12680.0          France

[541909 rows x 6 columns]>

In [17]:
ds.describe().T

,count,mean,std,min,25%,50%,75%,max
Quantity,541909.0,9.552250,218.081158,-80995.00,1.00,3.00,10.00,80995.0
UnitPrice,541909.0,4.611114,96.759853,-11062.06,1.25,2.08,4.13,38970.0
CustomerID,406829.0,15287.690570,1713.600303,12346.00,13953.00,15152.00,16791.00,18287.0

In [18]:
ds.columns

Index(['Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID',
       'Country'],
      dtype='object')

In [19]:
# Información base
print("Fecha mínima:", ds["InvoiceDate"].min())
print("Fecha máxima:", ds["InvoiceDate"].max())
print("Clientes únicos:", ds["CustomerID"].nunique())
print("Productos únicos:", ds["Description"].nunique())
print("Países:", ds["Country"].nunique())
ds["InvoiceDate"] = pd.to_datetime(ds["InvoiceDate"], errors="coerce")
print("Productos únicos:", ds["Description"].nunique())
print("Países:", ds["Country"].nunique())
print(f"Rango de fechas: {ds['InvoiceDate'].min().date()} → {ds['InvoiceDate'].max().date()}")

Fecha mínima: 1/10/2011 10:04
Fecha máxima: 9/9/2011 9:52
Clientes únicos: 4372
Productos únicos: 4223
Países: 38
Productos únicos: 4223
Países: 38
Rango de fechas: 2010-12-01 → 2011-12-09

# Feature Engineering

In [20]:
feature_engineer = FeatureEngineer(ds)

In [21]:
df_engineered = feature_engineer.run()

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\src\app\train\feature_engineer.py:52: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(self.historial_compra)   # <-- ahora acepta g

In [22]:
df_engineered

,Description,InvoiceDate,Country,Quantity,Revenue,UnitPrice,CustomerID,n_past_invoices,prev_date,recency_days,spend_prior,qty_prior,avg_ticket_prior,avg_qty_per_invoice_prior,next_date,days_to_next,y_repurchase_30d
0,MEDIUM CERAMIC TOP STORAGE JAR,2011-01-18 10:01:00,United Kingdom,74215,77183.60,1.04,12346.0,0,NaT,9999,0.00,0,0.000000,0.000000,2011-01-18 10:17:00,0.0,1
1,MEDIUM CERAMIC TOP STORAGE JAR,2011-01-18 10:17:00,United Kingdom,-74215,-77183.60,1.04,12346.0,1,2011-01-18 10:01:00,0,77183.60,74215,77183.600000,74215.000000,NaT,NaN,0
2,3D DOG PICTURE PLAYING CARDS,2010-12-07 14:57:00,Iceland,24,70.80,2.95,12347.0,0,NaT,9999,0.00,0,0.000000,0.000000,2010-12-07 14:57:00,0.0,1
3,AIRLINE BAG VINTAGE JET SET BROWN,2010-12-07 14:57:00,Iceland,4,17.00,4.25,12347.0,1,2010-12-07 14:57:00,0,70.80,24,70.800000,24.000000,2010-12-07 14:57:00,0.0,1
4,ALARM CLOCK BAKELIKE CHOCOLATE,2010-12-07 14:57:00,Iceland,4,15.00,3.75,12347.0,2,2010-12-07 14:57:00,0,87.80,28,43.900000,14.000000,2010-12-07 14:57:00,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
396480,SWISS CHALET TREE DECORATION,2011-10-12 10:23:00,United Kingdom,24,6.96,0.29,18287.0,63,2011-10-12 10:23:00,0,1739.84,1442,27.616508,22.888889,2011-10-12 10:23:00,0.0,1
396481,TREE T-LIGHT HOLDER WILLIE WINKIE,2011-10-12 10:23:00,United Kingdom,12,19.80,1.65,18287.0,64,2011-10-12 10:23:00,0,1746.80,1466,27.293750,22.906250,2011-10-28 09:29:00,15.0,1
396482,PAINTED METAL STAR WITH HOLLY BELLS,2011-10-28 09:29:00,United Kingdom,48,18.72,0.39,18287.0,65,2011-10-12 10:23:00,15,1766.60,1478,27.178462,22.738462,2011-10-28 09:29:00,0.0,1
396483,SET OF 3 WOODEN SLEIGH DECORATIONS,2011-10-28 09:29:00,United Kingdom,36,45.00,1.25,18287.0,66,2011-10-28 09:29:00,0,1785.32,1526,27.050303,23.121212,2011-10-28 09:29:00,0.0,1
396484,SWISS CHALET TREE DECORATION,2011-10-28 09:29:00,United Kingdom,24,6.96,0.29,18287.0,67,2011-10-28 09:29:00,0,1830.32,1562,27.318209,23.313433,NaT,NaN,0

# Modelando con MLFlow

In [23]:
import mlflow


experiment_name = "recompra-LogReg"
mlflow.set_tracking_uri("http://127.0.0.1:5000")
mlflow.set_experiment(experiment_name)

# Enable autologging for sklearn models
mlflow.sklearn.autolog(
    log_input_examples=True,
    log_model_signatures=True,
    log_models=True,
    disable=False,
    exclusive=False,
    disable_for_unsupported_versions=False,
    silent=False,
    max_tuning_runs=5
)

In [24]:
num_feats = [
    'recency_days','n_past_invoices','spend_prior','qty_prior',
    'avg_ticket_prior','avg_qty_per_invoice_prior','UnitPrice','Quantity','Revenue'
]
cat_feats = ['Country']

In [25]:


model = LogisticRegression(max_iter=500)

# 3) Instancia y entrena
trainer = TrainMlflow(
    df=df_engineered,
    numeric_features=num_feats,
    categorical_features=cat_feats,
    target_column='y_repurchase_30d',
    model=model,
    mlflow_setup={"tracking_uri": "file:./mlruns", "experiment_name": "OnlineRetail"}
)

pipeline, run_id = trainer.train()
trainer.pipeline = pipeline                  # <- necesario para save_model()
trainer.save_model("models/model.pkl")       # ✅ Modelo guardado en models/model.pkl

Rango total: 2010-12-01 08:26:00 → 2011-12-09 12:50:00 | cutoff: 2011-11-09 12:50:00
train_end: 2011-09-01 00:00:00
train: 224017 | test: 104368
pos_rate train=0.973 | test=0.979

2025/09/27 19:14:28 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 19:14:30 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1325.33it/s]
2025/09/27 19:14:59 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 19:15:01 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."

MLflow Run ID: 67015b171e844dbfbcdf4999f95f116d
Tracking URI: http://127.0.0.1:5000
Train Accuracy: 0.9728
Test Accuracy: 0.9794
🏃 View run enchanting-cod-926 at: http://127.0.0.1:5000/#/experiments/2/runs/67015b171e844dbfbcdf4999f95f116d
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2
✅ Modelo guardado en models/model.pkl

'models/model.pkl'

In [26]:
mlflow.set_experiment("recompra-optuna")

params = {
            'solver': ('categorical', ['lbfgs', 'liblinear', 'saga']),
            'C':      ('float', 1e-3, 1e2, True),
            'max_iter': ('int', 300, 1500),
            'class_weight': ('categorical', [None, 'balanced']),
            # solver-specific penalties are tricky to encode generically—start simple with l2
            'penalty': ('categorical', ['l2']),
}

trainer = TrainOptuna(
    df=df_engineered,
    numeric_features=num_feats,
    categorical_features=cat_feats,
    target_column='y_repurchase_30d',
    model_class=LogisticRegression,
    model_params={},                 
    n_trials=30,                     
    optimization_metric='roc_auc',   
    param_distributions=params,
)

best_pipeline, best_run_id, study = trainer.train()   # runs Optuna + logs to MLflow
trainer.save_model("models/modeloptuna.pkl")

[I 2025-09-27 19:15:02,892] A new study created in memory with name: optuna_LogisticRegression
c:\Users\gabri\OneDrive\ProyectoFinalMLOps\src\app\train\train_mlflow_advance.py:247: ExperimentalWarning: MLflowCallback is experimental (supported from v1.4.0). The interface can change in the future.
  mlflow_callback = MLflowCallback(
2025/09/27 19:15:02 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '6042f44e9ada4c65a07989c92d8b2669', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

Rango total: 2010-12-01 08:26:00 → 2011-12-09 12:50:00 | cutoff: 2011-11-09 12:50:00
train_end: 2011-09-01 00:00:00
train: 224017 | test: 104368
pos_rate train=0.973 | test=0.979
Starting Optuna optimization with 30 trials...
Optimizing for: roc_auc
Model type: LogisticRegression

2025/09/27 19:15:07 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
2025/09/27 19:19:06 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1282.05it/s]

🏃 View run sedate-horse-416 at: http://127.0.0.1:5000/#/experiments/3/runs/6042f44e9ada4c65a07989c92d8b2669
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/3

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 19:19:20 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 19:19:20,484] Trial 0 finished with value: 0.6683206573525065 and parameters: {'solver': 'saga', 'C': 0.002745355180497904, 'max_iter': 1209, 'class_weight': None, 'penalty': 'l2'}. Best is trial 0 with value: 0.6683206573525065.
2025/09/27 19:19:20 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '17fbef7c969846948815408bc1525923', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 0 at: http://127.0.0.1:5000/#/experiments/4/runs/cbc7b2db61c74dcaac28c71afb1bd54e
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 19:19:23 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 19:19:26 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 2146.68it/s]

🏃 View run illustrious-owl-670 at: http://127.0.0.1:5000/#/experiments/4/runs/17fbef7c969846948815408bc1525923
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 19:19:36 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 19:19:36,137] Trial 1 finished with value: 0.6811016449026688 and parameters: {'solver': 'lbfgs', 'C': 2.068726336881072, 'max_iter': 1073, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 1 with value: 0.6811016449026688.
2025/09/27 19:19:36 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'a5f9d7b07bad406bb7516c71bd4aea17', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 1 at: http://127.0.0.1:5000/#/experiments/4/runs/dad090d42de444adbec5e7614c4900b2
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 19:19:39 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
2025/09/27 19:22:46 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 646.29it/s]

🏃 View run glamorous-mole-17 at: http://127.0.0.1:5000/#/experiments/4/runs/a5f9d7b07bad406bb7516c71bd4aea17
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 19:22:58 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 19:22:58,405] Trial 2 finished with value: 0.6635918235495923 and parameters: {'solver': 'saga', 'C': 0.33815491653060314, 'max_iter': 1021, 'class_weight': None, 'penalty': 'l2'}. Best is trial 1 with value: 0.6811016449026688.
2025/09/27 19:22:58 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '3a2f38f67565455799cb4132db32c1e8', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 2 at: http://127.0.0.1:5000/#/experiments/4/runs/b3b5cf92aab84172b9c99f850688202f
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 19:23:01 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 19:23:04 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 2130.02it/s]

🏃 View run legendary-owl-282 at: http://127.0.0.1:5000/#/experiments/4/runs/3a2f38f67565455799cb4132db32c1e8
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 19:23:13 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 19:23:13,838] Trial 3 finished with value: 0.6810127255308411 and parameters: {'solver': 'lbfgs', 'C': 26.51083567011024, 'max_iter': 629, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 1 with value: 0.6811016449026688.
2025/09/27 19:23:14 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '243d1e9dec59469e9626108d2bb4b3f5', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 3 at: http://127.0.0.1:5000/#/experiments/4/runs/5d47cd8eaa1e4243848992955ded96bf
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 19:23:17 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
2025/09/27 19:27:12 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 957.76it/s]

🏃 View run bustling-robin-475 at: http://127.0.0.1:5000/#/experiments/4/runs/243d1e9dec59469e9626108d2bb4b3f5
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 19:27:24 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 19:27:25,042] Trial 4 finished with value: 0.6807139081429946 and parameters: {'solver': 'saga', 'C': 32.93391411219699, 'max_iter': 1201, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 1 with value: 0.6811016449026688.
2025/09/27 19:27:25 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'b3f350cbf5004e4c80efeff888510caa', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 4 at: http://127.0.0.1:5000/#/experiments/4/runs/a26decb60686495fafb02a8e140d47d1
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 19:27:29 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 19:27:32 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 999.63it/s]

🏃 View run dapper-chimp-787 at: http://127.0.0.1:5000/#/experiments/4/runs/b3f350cbf5004e4c80efeff888510caa
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 19:27:45 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 19:27:45,314] Trial 5 finished with value: 0.671119460079934 and parameters: {'solver': 'lbfgs', 'C': 0.008511932927615259, 'max_iter': 565, 'class_weight': None, 'penalty': 'l2'}. Best is trial 1 with value: 0.6811016449026688.
2025/09/27 19:27:45 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '4a28cadb72f24ee59d81c6e1ffa48d92', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 5 at: http://127.0.0.1:5000/#/experiments/4/runs/279ec6cf0b4b48188ed29ea6ff8bd8af
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 19:27:49 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 19:27:52 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1870.91it/s]

🏃 View run carefree-worm-451 at: http://127.0.0.1:5000/#/experiments/4/runs/4a28cadb72f24ee59d81c6e1ffa48d92
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 19:28:05 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 19:28:05,727] Trial 6 finished with value: 0.6810666057036243 and parameters: {'solver': 'lbfgs', 'C': 90.92640631679241, 'max_iter': 667, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 1 with value: 0.6811016449026688.
2025/09/27 19:28:05 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'bb386ee1f0ea464c93f4d84e99027b43', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 6 at: http://127.0.0.1:5000/#/experiments/4/runs/6435d01a9a154d02b9a52406851f6dd5
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 19:28:10 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 19:28:12 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1062.66it/s]

🏃 View run blushing-hound-106 at: http://127.0.0.1:5000/#/experiments/4/runs/bb386ee1f0ea464c93f4d84e99027b43
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 19:28:24 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 19:28:24,786] Trial 7 finished with value: 0.6808932824146184 and parameters: {'solver': 'liblinear', 'C': 41.36750946298025, 'max_iter': 1304, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 1 with value: 0.6811016449026688.
2025/09/27 19:28:25 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '29f0da8d5d0041748313d2717a94b455', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 7 at: http://127.0.0.1:5000/#/experiments/4/runs/72c696ce35ea4761b787e7bfde406d5a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 19:28:28 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
2025/09/27 19:30:35 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1855.53it/s]

🏃 View run youthful-ox-379 at: http://127.0.0.1:5000/#/experiments/4/runs/29f0da8d5d0041748313d2717a94b455
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 19:30:47 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 19:30:47,409] Trial 8 finished with value: 0.656396002310801 and parameters: {'solver': 'saga', 'C': 0.030943656166713098, 'max_iter': 598, 'class_weight': None, 'penalty': 'l2'}. Best is trial 1 with value: 0.6811016449026688.
2025/09/27 19:30:47 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '62c237d326a84d27a864fde15c13f5d4', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 8 at: http://127.0.0.1:5000/#/experiments/4/runs/93fc9c614b3241108c6abe9946a52c41
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 19:30:51 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 19:30:53 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 2140.89it/s]

🏃 View run overjoyed-worm-591 at: http://127.0.0.1:5000/#/experiments/4/runs/62c237d326a84d27a864fde15c13f5d4
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 19:31:06 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 19:31:06,346] Trial 9 finished with value: 0.681060099074725 and parameters: {'solver': 'lbfgs', 'C': 0.2719603648887427, 'max_iter': 339, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 1 with value: 0.6811016449026688.
2025/09/27 19:31:06 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '4b5cbb6bd486467ca550bb956d16a8c3', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 9 at: http://127.0.0.1:5000/#/experiments/4/runs/20e72123e94146c596a041a25ceeb4a9
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 19:31:09 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 19:31:12 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 803.31it/s]

🏃 View run adventurous-crow-6 at: http://127.0.0.1:5000/#/experiments/4/runs/4b5cbb6bd486467ca550bb956d16a8c3
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 19:31:24 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 19:31:24,779] Trial 10 finished with value: 0.6809073299894759 and parameters: {'solver': 'liblinear', 'C': 2.1920910687793644, 'max_iter': 1469, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 1 with value: 0.6811016449026688.
2025/09/27 19:31:25 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '17003537fd6241f8a4b71a49c5523b2b', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 10 at: http://127.0.0.1:5000/#/experiments/4/runs/1c476a90890944ed9922e76b9f6ab2e1
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 19:31:29 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 19:31:31 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1006.07it/s]

🏃 View run invincible-snipe-213 at: http://127.0.0.1:5000/#/experiments/4/runs/17003537fd6241f8a4b71a49c5523b2b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 19:31:42 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 19:31:42,456] Trial 11 finished with value: 0.6811453596069125 and parameters: {'solver': 'lbfgs', 'C': 2.999879534951426, 'max_iter': 891, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 11 with value: 0.6811453596069125.
2025/09/27 19:31:42 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'f4ac5d82a2f24e09a3562ea70569fec5', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 11 at: http://127.0.0.1:5000/#/experiments/4/runs/c68ea4e697544116af37c1cd9434852b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 19:31:46 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 19:31:48 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1315.48it/s]

🏃 View run capable-kite-307 at: http://127.0.0.1:5000/#/experiments/4/runs/f4ac5d82a2f24e09a3562ea70569fec5
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 19:32:00 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 19:32:00,777] Trial 12 finished with value: 0.6810787122253228 and parameters: {'solver': 'lbfgs', 'C': 2.4069882246393006, 'max_iter': 928, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 11 with value: 0.6811453596069125.
2025/09/27 19:32:01 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'd1914c64b44c4b0e8f4fb326c2215d32', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 12 at: http://127.0.0.1:5000/#/experiments/4/runs/4cb411400d9b44d399d2076f7ff1855a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 19:32:04 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 19:32:07 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1442.90it/s]

🏃 View run casual-bug-297 at: http://127.0.0.1:5000/#/experiments/4/runs/d1914c64b44c4b0e8f4fb326c2215d32
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 19:32:19 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 19:32:19,323] Trial 13 finished with value: 0.6811631298118896 and parameters: {'solver': 'lbfgs', 'C': 2.7901558152197845, 'max_iter': 806, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 13 with value: 0.6811631298118896.
2025/09/27 19:32:19 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '1bdd5f7eb6674ef4abdccfdf9e76fc2f', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 13 at: http://127.0.0.1:5000/#/experiments/4/runs/6633fb8be5524439b256c5fd44f812f0
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 19:32:23 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 19:32:25 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1450.38it/s]

🏃 View run silent-gnat-1000 at: http://127.0.0.1:5000/#/experiments/4/runs/1bdd5f7eb6674ef4abdccfdf9e76fc2f
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 19:32:37 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 19:32:37,336] Trial 14 finished with value: 0.6809883757935599 and parameters: {'solver': 'lbfgs', 'C': 5.20737146621182, 'max_iter': 827, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 13 with value: 0.6811631298118896.
2025/09/27 19:32:37 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'e515b318ff0c402cb22d7b1aa01a9d3e', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 14 at: http://127.0.0.1:5000/#/experiments/4/runs/70fb856cf46c438bac05ee16e30a573f
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 19:32:42 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 19:32:44 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1152.01it/s]

🏃 View run bouncy-foal-973 at: http://127.0.0.1:5000/#/experiments/4/runs/e515b318ff0c402cb22d7b1aa01a9d3e
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 19:32:59 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 19:32:59,976] Trial 15 finished with value: 0.6810585362079796 and parameters: {'solver': 'lbfgs', 'C': 0.26913374483831254, 'max_iter': 785, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 13 with value: 0.6811631298118896.
2025/09/27 19:33:00 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'ea5ce0a179554ebc9958c1cd3ab6c36e', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 15 at: http://127.0.0.1:5000/#/experiments/4/runs/ba41a831757a45e095db350947b05861
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 19:33:05 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 19:33:07 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1141.48it/s]

🏃 View run likeable-worm-250 at: http://127.0.0.1:5000/#/experiments/4/runs/ea5ce0a179554ebc9958c1cd3ab6c36e
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 19:33:20 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 19:33:20,506] Trial 16 finished with value: 0.6808971189563082 and parameters: {'solver': 'liblinear', 'C': 8.128633724935295, 'max_iter': 373, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 13 with value: 0.6811631298118896.
2025/09/27 19:33:20 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '22d84fe9d6ec42aeac886cc4bf400081', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 16 at: http://127.0.0.1:5000/#/experiments/4/runs/cc1344d53cec4f4abd4a46aef0829ccc
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 19:33:24 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 19:33:27 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1352.69it/s]

🏃 View run judicious-hawk-888 at: http://127.0.0.1:5000/#/experiments/4/runs/22d84fe9d6ec42aeac886cc4bf400081
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 19:33:39 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 19:33:39,348] Trial 17 finished with value: 0.6810391940233316 and parameters: {'solver': 'lbfgs', 'C': 0.6929420546570447, 'max_iter': 938, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 13 with value: 0.6811631298118896.
2025/09/27 19:33:39 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'def200e7877447fe86a707f71a21b8c3', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 17 at: http://127.0.0.1:5000/#/experiments/4/runs/72eacce77b6e41bc93066a5a9f8a84db
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 19:33:43 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 19:33:45 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1359.58it/s]

🏃 View run bright-bug-370 at: http://127.0.0.1:5000/#/experiments/4/runs/def200e7877447fe86a707f71a21b8c3
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 19:33:56 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 19:33:56,556] Trial 18 finished with value: 0.6725222491737504 and parameters: {'solver': 'lbfgs', 'C': 0.03326194931539057, 'max_iter': 754, 'class_weight': None, 'penalty': 'l2'}. Best is trial 13 with value: 0.6811631298118896.
2025/09/27 19:33:56 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '76161ccffd49416eaea14f236a6db56c', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 18 at: http://127.0.0.1:5000/#/experiments/4/runs/23f3661e118c4ae898bfed52e930acad
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 19:34:00 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 19:34:02 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1055.09it/s]

🏃 View run upbeat-fly-214 at: http://127.0.0.1:5000/#/experiments/4/runs/76161ccffd49416eaea14f236a6db56c
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 19:34:14 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 19:34:14,434] Trial 19 finished with value: 0.6810075539455467 and parameters: {'solver': 'liblinear', 'C': 0.08306178855134527, 'max_iter': 493, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 13 with value: 0.6811631298118896.
2025/09/27 19:34:14 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'c2e2b0805a38429ba899c871f2cdb84c', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 19 at: http://127.0.0.1:5000/#/experiments/4/runs/6ab026779a7f42a2b8e2506681fec3b1
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 19:34:18 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 19:34:20 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1260.85it/s]

🏃 View run beautiful-mule-394 at: http://127.0.0.1:5000/#/experiments/4/runs/c2e2b0805a38429ba899c871f2cdb84c
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 19:34:33 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 19:34:33,795] Trial 20 finished with value: 0.6810415041499785 and parameters: {'solver': 'lbfgs', 'C': 8.640993544167616, 'max_iter': 1048, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 13 with value: 0.6811631298118896.
2025/09/27 19:34:34 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'a6901d30164f4a82a48754d2b4c39cc2', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 20 at: http://127.0.0.1:5000/#/experiments/4/runs/86c8b7d6a374435bb7843e4cf833189a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 19:34:36 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 19:34:39 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1735.03it/s]

🏃 View run carefree-mink-162 at: http://127.0.0.1:5000/#/experiments/4/runs/a6901d30164f4a82a48754d2b4c39cc2
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 19:34:47 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 19:34:47,721] Trial 21 finished with value: 0.6809800101278322 and parameters: {'solver': 'lbfgs', 'C': 1.2842227913868287, 'max_iter': 1064, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 13 with value: 0.6811631298118896.
2025/09/27 19:34:47 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'd2513e93dbd2451eb082d4e8e5d0a653', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 21 at: http://127.0.0.1:5000/#/experiments/4/runs/0922940b8aee44b0ab24bc30dde37a44
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 19:34:50 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 19:34:52 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1418.91it/s]

🏃 View run adorable-elk-921 at: http://127.0.0.1:5000/#/experiments/4/runs/d2513e93dbd2451eb082d4e8e5d0a653
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 19:35:00 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 19:35:00,951] Trial 22 finished with value: 0.6811353217193319 and parameters: {'solver': 'lbfgs', 'C': 4.118967801068041, 'max_iter': 920, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 13 with value: 0.6811631298118896.
2025/09/27 19:35:01 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '99ae2a5bbbeb4d3f8e5b738c8b55f8c5', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 22 at: http://127.0.0.1:5000/#/experiments/4/runs/fb0f997208ca4dfc9c3e7ea01dab5e89
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 19:35:03 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 19:35:06 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1519.36it/s]

🏃 View run brawny-wolf-335 at: http://127.0.0.1:5000/#/experiments/4/runs/99ae2a5bbbeb4d3f8e5b738c8b55f8c5
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 19:35:14 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 19:35:14,450] Trial 23 finished with value: 0.6810513780048978 and parameters: {'solver': 'lbfgs', 'C': 12.494366263282334, 'max_iter': 885, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 13 with value: 0.6811631298118896.
2025/09/27 19:35:14 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'eb6c0bdac61f46219344477ba3e71159', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 23 at: http://127.0.0.1:5000/#/experiments/4/runs/8212384df6504c5192a82316c5e188d6
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 19:35:17 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 19:35:19 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1297.40it/s]

🏃 View run trusting-shoat-242 at: http://127.0.0.1:5000/#/experiments/4/runs/eb6c0bdac61f46219344477ba3e71159
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 19:35:27 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 19:35:27,052] Trial 24 finished with value: 0.6809844663484649 and parameters: {'solver': 'lbfgs', 'C': 0.8522682276254427, 'max_iter': 728, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 13 with value: 0.6811631298118896.
2025/09/27 19:35:27 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '080d3b50dea44299a746bbc7d5f7940b', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 24 at: http://127.0.0.1:5000/#/experiments/4/runs/52c2f8cfe51e48ffa9252c8f14bc823e
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 19:35:30 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 19:35:31 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 966.78it/s]

🏃 View run skittish-bird-303 at: http://127.0.0.1:5000/#/experiments/4/runs/080d3b50dea44299a746bbc7d5f7940b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 19:35:40 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 19:35:40,730] Trial 25 finished with value: 0.6810551416431827 and parameters: {'solver': 'lbfgs', 'C': 7.03695089843657, 'max_iter': 873, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 13 with value: 0.6811631298118896.
2025/09/27 19:35:40 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '449296e889a743829afde83f88b311c5', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 25 at: http://127.0.0.1:5000/#/experiments/4/runs/545c5e7fcd2349088d863d67c738d058
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 19:35:43 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 19:35:44 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 2002.33it/s]

🏃 View run shivering-skunk-102 at: http://127.0.0.1:5000/#/experiments/4/runs/449296e889a743829afde83f88b311c5
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 19:35:53 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 19:35:53,555] Trial 26 finished with value: 0.6739158797773095 and parameters: {'solver': 'lbfgs', 'C': 3.448477047273275, 'max_iter': 940, 'class_weight': None, 'penalty': 'l2'}. Best is trial 13 with value: 0.6811631298118896.
2025/09/27 19:35:53 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '0af45a21516e4091a0bc2f72b318d06b', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 26 at: http://127.0.0.1:5000/#/experiments/4/runs/f93e778036014df78b98220f092d087f
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 19:35:56 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 19:35:58 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1649.91it/s]

🏃 View run rebellious-moth-415 at: http://127.0.0.1:5000/#/experiments/4/runs/0af45a21516e4091a0bc2f72b318d06b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 19:36:06 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 19:36:06,632] Trial 27 finished with value: 0.6812715645139523 and parameters: {'solver': 'lbfgs', 'C': 0.5276644943277047, 'max_iter': 1182, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 27 with value: 0.6812715645139523.
2025/09/27 19:36:06 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID 'c3b62dbfc6704a34b369c58a8aa27f8c', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 27 at: http://127.0.0.1:5000/#/experiments/4/runs/ea7ce3fa6d934b9b9e28e48404084f12
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 19:36:09 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
2025/09/27 19:40:05 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1716.77it/s]

🏃 View run unique-newt-911 at: http://127.0.0.1:5000/#/experiments/4/runs/c3b62dbfc6704a34b369c58a8aa27f8c
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 19:40:15 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 19:40:15,626] Trial 28 finished with value: 0.6806432647435166 and parameters: {'solver': 'saga', 'C': 0.10758002337665039, 'max_iter': 1175, 'class_weight': 'balanced', 'penalty': 'l2'}. Best is trial 27 with value: 0.6812715645139523.
2025/09/27 19:40:15 INFO mlflow.utils.autologging_utils: Created MLflow autologging run with ID '2074339983c441a8b178e059f12e1977', which will track hyperparameters, performance metrics, model artifacts, and lineage information for the current sklearn workflow

🏃 View run 28 at: http://127.0.0.1:5000/#/experiments/4/runs/b9dfec2884a24c0bb81b9f8b27be7714
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

2025/09/27 19:40:19 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 19:40:20 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1617.01it/s]

🏃 View run welcoming-wolf-988 at: http://127.0.0.1:5000/#/experiments/4/runs/2074339983c441a8b178e059f12e1977
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 19:40:28 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
[I 2025-09-27 19:40:28,987] Trial 29 finished with value: 0.6542630035992366 and parameters: {'solver': 'liblinear', 'C': 0.0022853747374111722, 'max_iter': 1314, 'class_weight': None, 'penalty': 'l2'}. Best is trial 27 with value: 0.6812715645139523.

🏃 View run 29 at: http://127.0.0.1:5000/#/experiments/4/runs/8f4c28a03fd341edb28d6440ae30f40b
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4

Optimization complete!
Best roc_auc: 0.6813
Best parameters: {'solver': 'lbfgs', 'C': 0.5276644943277047, 'max_iter': 1182, 'class_weight': 'balanced', 'penalty': 'l2'}

2025/09/27 19:40:32 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
2025/09/27 19:40:34 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1429.69it/s]
2025/09/27 19:40:44 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:246: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(
2025/09/27 19:40:46 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."
c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
  warnings.warn(
2025/09/27 19:40:49 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 1904.77it/s]
2025/09/27 19:40:53 WARNING mlflow.utils.autologging_utils: MLflow autologging encountered a warning: "c:\Users\gabri\OneDrive\ProyectoFinalMLOps\.venv\Lib\site-packages\mlflow\types\utils.py:452: UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details."

Best Model MLflow Run ID: f36331862f434944bc737c556e4dde3a
Tracking URI: http://127.0.0.1:5000
Train Accuracy: 0.4427
Test Accuracy: 0.6139
🏃 View run best_model_LogisticRegression at: http://127.0.0.1:5000/#/experiments/4/runs/f36331862f434944bc737c556e4dde3a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
✅ Modelo guardado en models/modeloptuna.pkl

'models/modeloptuna.pkl'

In [27]:
from sklearn.metrics import roc_auc_score, average_precision_score, precision_recall_curve, f1_score
y_proba = best_pipeline.predict_proba(X_test)[:,1]
roc = roc_auc_score(y_test, y_proba)
pr  = average_precision_score(y_test, y_proba)
prec, rec, thr = precision_recall_curve(y_test, y_proba)

# choose threshold by best F1, for example
import numpy as np
f1s = [f1_score(y_test, (y_proba>=t).astype(int)) for t in thr]
t_star = float(thr[np.argmax(f1s)])
print(roc, pr, t_star)

NameError: name 'X_test' is not defined